In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as Fh
import torch.optim as optim

In [8]:
def myloss(theta,i,show=False):
    global A
    beta = torch.ones([m, n], dtype=torch.float64)*(2**i)
    A = torch.sigmoid(beta*theta)
    Anorm = torch.sum(A*A,0)**0.5
    Anorm = Anorm.repeat(m,1)
    A = A/Anorm
    M = torch.matmul(torch.t(A), A)
    if (show):
        print(A)
    l1 = torch.norm(M-I)**2
    l2 = lam*abs(torch.norm(theta)**2-1)  
    return l1+l2,l1

In [9]:
m = 16
n = 40
I = torch.eye(n, dtype=torch.float64)
lam = 0.01

# beta = torch.ones([m, n], dtype=torch.float64, requires_grad=True)
x = torch.rand([m, n], dtype=torch.float64, requires_grad=True)
# print(x)
# x=x-0.5
# print(x)
# temp = torch.norm(x)
# x.data = x.data/temp

# y, fnorm = myloss(x,0,True)
# print("hey1")
# print(y)
# print(A)
# print("hey2")

tensor([[0.2088, 0.2856, 0.2760, 0.2530, 0.2635, 0.2429, 0.2794, 0.2339, 0.2544,
         0.2335, 0.3022, 0.2105, 0.2506, 0.2548, 0.2038, 0.2068, 0.2657, 0.2366,
         0.2528, 0.2526, 0.2803, 0.2713, 0.2809, 0.2911, 0.2263, 0.2800, 0.2088,
         0.2865, 0.2278, 0.2386, 0.2070, 0.3020, 0.2345, 0.2239, 0.2158, 0.2746,
         0.2193, 0.2151, 0.2201, 0.2666],
        [0.2698, 0.2041, 0.2268, 0.2888, 0.2072, 0.2862, 0.2282, 0.2980, 0.2275,
         0.3007, 0.2562, 0.2812, 0.2873, 0.2703, 0.2485, 0.2228, 0.2851, 0.2680,
         0.2754, 0.2074, 0.2733, 0.2589, 0.2224, 0.2062, 0.2849, 0.2268, 0.2576,
         0.2807, 0.2507, 0.1975, 0.2707, 0.2600, 0.2901, 0.2230, 0.2171, 0.1991,
         0.2255, 0.2148, 0.2481, 0.2826],
        [0.2705, 0.2133, 0.2131, 0.2684, 0.2579, 0.2859, 0.2365, 0.2213, 0.2695,
         0.2180, 0.2190, 0.2583, 0.2322, 0.2408, 0.2422, 0.2811, 0.2718, 0.2205,
         0.2760, 0.2458, 0.2012, 0.2823, 0.2260, 0.2874, 0.2905, 0.2340, 0.2725,
         0.2038, 0.2806, 

       grad_fn=<DivBackward0>)
hey2


In [10]:
optimizer = torch.optim.Adam([x])

In [11]:

# x = torch.tensor(.0, requires_grad=True)
# y = (x-2)**2



# optimizer = torch.optim.SGD([x], lr=0.0001)


# initilizae
# print(x,y)
for j in range(10):
#     if (j!=0):
#         x.data = x.data/2
#     temp = torch.norm(x)
#     x.data = x.data/temp
    for i in range(40000):
        optimizer.zero_grad()
        y, fnorm = myloss(x,0)
        y.backward(retain_graph=True)
        optimizer.step()
        
#         beta = torch.ones([m, n], dtype=torch.float64)*(2**j)
#         A = torch.sigmoid(beta*x)
#         Anorm = torch.sum(A*A,0)**0.5
#         Anorm = Anorm.repeat(m,1)
#         A = A/Anorm
#         nt = -torch.log(1/A-1)/beta
#         x.data = nt.data
#         A = torch.sigmoid(beta*x)
        if (i==1000):
            print(A)
#         temp = torch.norm(x)
#         x.data = x.data/temp
        
        if (i + 1) % 1000 == 0:
            print('beta:',2**j,' epoch:',i + 1,' loss:',y.item(),' F-norm:',fnorm.item())

beta: 1  epoch: 1000  loss: 964.7941201048086  F-norm: 951.7792066181577
tensor([[0.1044, 0.3389, 0.3561, 0.3192, 0.3173, 0.1125, 0.3360, 0.1113, 0.3195,
         0.1103, 0.3456, 0.1011, 0.1261, 0.3538, 0.0982, 0.0999, 0.3340, 0.1095,
         0.3191, 0.3543, 0.3786, 0.3348, 0.3362, 0.3600, 0.1081, 0.3560, 0.1013,
         0.3797, 0.1130, 0.1101, 0.1004, 0.3881, 0.1085, 0.1009, 0.1071, 0.3550,
         0.1066, 0.1034, 0.1095, 0.3345],
        [0.3343, 0.0983, 0.1097, 0.3216, 0.1014, 0.3378, 0.1103, 0.3625, 0.1084,
         0.3632, 0.3365, 0.3202, 0.4092, 0.3543, 0.1115, 0.1061, 0.3375, 0.3169,
         0.3167, 0.1038, 0.3766, 0.3351, 0.1090, 0.1046, 0.3369, 0.1105, 0.3352,
         0.3775, 0.1171, 0.0955, 0.3340, 0.3763, 0.3383, 0.1009, 0.1079, 0.1029,
         0.1091, 0.1035, 0.1172, 0.3373],
        [0.3360, 0.1026, 0.1054, 0.3183, 0.3198, 0.3393, 0.1126, 0.1086, 0.3187,
         0.1067, 0.1027, 0.3198, 0.1271, 0.1130, 0.1102, 0.3373, 0.3353, 0.1050,
         0.3200, 0.1138, 0.1103, 

beta: 2  epoch: 21000  loss: 166.20006079253133  F-norm: 101.90530067497097
beta: 2  epoch: 22000  loss: 166.20006079253125  F-norm: 101.90530067327396
beta: 2  epoch: 23000  loss: 166.20006079253136  F-norm: 101.90530067420377
beta: 2  epoch: 24000  loss: 166.20006079253147  F-norm: 101.90530067429849
beta: 2  epoch: 25000  loss: 166.20006079253142  F-norm: 101.90530067162027
beta: 2  epoch: 26000  loss: 166.20006079253116  F-norm: 101.90530067566709
beta: 2  epoch: 27000  loss: 166.2000607925313  F-norm: 101.90530070579844
beta: 2  epoch: 28000  loss: 166.20006079253142  F-norm: 101.90530066484614
beta: 2  epoch: 29000  loss: 166.20006079253122  F-norm: 101.90530067432532
beta: 2  epoch: 30000  loss: 166.20006079253142  F-norm: 101.90530067299562
beta: 2  epoch: 31000  loss: 166.2000607925313  F-norm: 101.90530067259897
beta: 2  epoch: 32000  loss: 166.2000607925311  F-norm: 101.90530067359401
beta: 2  epoch: 33000  loss: 166.200060793511  F-norm: 101.90548410586327
beta: 2  epoch: 3

       grad_fn=<DivBackward0>)
beta: 8  epoch: 2000  loss: 166.20006079253153  F-norm: 101.90529709953334
beta: 8  epoch: 3000  loss: 166.20006079253156  F-norm: 101.90529706994099
beta: 8  epoch: 4000  loss: 166.20006079253125  F-norm: 101.90530035764837
beta: 8  epoch: 5000  loss: 166.20006079253142  F-norm: 101.90530062658578
beta: 8  epoch: 6000  loss: 166.20006079253153  F-norm: 101.90530063916731
beta: 8  epoch: 7000  loss: 166.20006079253116  F-norm: 101.90530067486112
beta: 8  epoch: 8000  loss: 166.20006079253125  F-norm: 101.90530065436786
beta: 8  epoch: 9000  loss: 166.20006079253125  F-norm: 101.90530067994409
beta: 8  epoch: 10000  loss: 166.20006079253108  F-norm: 101.90530067313014
beta: 8  epoch: 11000  loss: 166.20006079253127  F-norm: 101.90530067363923
beta: 8  epoch: 12000  loss: 166.20006079596467  F-norm: 101.90495729585027
beta: 8  epoch: 13000  loss: 166.20006079262106  F-norm: 101.90524513918233
beta: 8  epoch: 14000  loss: 166.20006079253136  F-norm: 101.9053

       grad_fn=<DivBackward0>)
beta: 16  epoch: 2000  loss: 166.20006079272974  F-norm: 101.90538326297006
beta: 16  epoch: 3000  loss: 166.2000608067017  F-norm: 101.90460305425925
beta: 16  epoch: 4000  loss: 166.200060792763  F-norm: 101.9052114522536
beta: 16  epoch: 5000  loss: 166.20006079253292  F-norm: 101.90529335668668
beta: 16  epoch: 6000  loss: 166.20006079253125  F-norm: 101.90530059648532
beta: 16  epoch: 7000  loss: 166.20006079253108  F-norm: 101.90530053343151
beta: 16  epoch: 8000  loss: 166.2000607925313  F-norm: 101.90530065368803
beta: 16  epoch: 9000  loss: 166.20006079253153  F-norm: 101.90530069579164
beta: 16  epoch: 10000  loss: 166.2000607925312  F-norm: 101.90530067426664
beta: 16  epoch: 11000  loss: 166.2000607925313  F-norm: 101.90530067353505
beta: 16  epoch: 12000  loss: 166.20006079253147  F-norm: 101.90530067369475
beta: 16  epoch: 13000  loss: 166.20006079253122  F-norm: 101.90530067327482
beta: 16  epoch: 14000  loss: 166.20006079253108  F-norm: 10

       grad_fn=<DivBackward0>)
beta: 32  epoch: 2000  loss: 166.2000607925312  F-norm: 101.90530067366366
beta: 32  epoch: 3000  loss: 166.20006139534757  F-norm: 101.90985105639244
beta: 32  epoch: 4000  loss: 166.20006080652644  F-norm: 101.90460740369744
beta: 32  epoch: 5000  loss: 166.20006079261003  F-norm: 101.90535272033766
beta: 32  epoch: 6000  loss: 166.20006079253142  F-norm: 101.90529946599956
beta: 32  epoch: 7000  loss: 166.2000607925312  F-norm: 101.9053006153818
beta: 32  epoch: 8000  loss: 166.20006079253125  F-norm: 101.9053006710708
beta: 32  epoch: 9000  loss: 166.20006079253096  F-norm: 101.90530067205971
beta: 32  epoch: 10000  loss: 166.2000607925312  F-norm: 101.9053007051862
beta: 32  epoch: 11000  loss: 166.2000607925312  F-norm: 101.90530070552143
beta: 32  epoch: 12000  loss: 166.20006079253136  F-norm: 101.9053006876768
beta: 32  epoch: 13000  loss: 166.20006079253125  F-norm: 101.90530067101425
beta: 32  epoch: 14000  loss: 166.2000607925313  F-norm: 101.

KeyboardInterrupt: 

In [12]:
beta = torch.ones([m, n], dtype=torch.float64)*(32)
C = torch.sigmoid(beta*x)
# print(C)
# B is the final sensing matrix
B=torch.round(C)
torch.set_printoptions(threshold=5000)
print(B)
# print((B!=0))

tensor([[3.5303e-48, 1.5944e-43, 1.0000e+00, 4.1059e-52, 6.3132e-49, 2.5352e-48,
         6.3034e-49, 3.0049e-46, 1.0000e+00, 9.1961e-44, 9.7455e-46, 8.7638e-44,
         1.0920e-48, 1.1228e-48, 1.8867e-43, 1.5690e-43, 1.0000e+00, 8.8292e-49,
         2.0152e-43, 1.8122e-43, 2.0303e-43, 3.2677e-43, 3.6366e-52, 2.1366e-43,
         3.4035e-52, 1.4732e-43, 8.7864e-49, 3.7110e-43, 1.5205e-48, 8.2233e-43,
         9.8964e-49, 1.0000e+00, 3.3234e-43, 1.3522e-48, 3.3856e-43, 1.7365e-43,
         1.8233e-43, 1.2532e-48, 4.3121e-52, 1.0000e+00],
        [1.9120e-48, 7.5918e-43, 4.1784e-43, 8.0501e-43, 8.1741e-43, 1.9053e-48,
         1.0193e-42, 1.0000e+00, 4.6827e-43, 1.0000e+00, 5.7285e-45, 1.0000e+00,
         1.0929e-42, 1.9373e-42, 1.7009e-48, 1.4705e-42, 4.7799e-43, 1.9640e-48,
         9.3038e-43, 1.8765e-48, 1.8901e-48, 1.0000e+00, 1.0429e-42, 1.7865e-48,
         9.4075e-43, 2.8268e-48, 1.0118e-42, 8.4749e-43, 1.9564e-48, 3.1233e-48,
         1.0500e-42, 4.4030e-43, 7.9390e-43, 9.2943

       grad_fn=<SigmoidBackward>)
tensor([[0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
         0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0